name: Repository Info Printer

on:
  push:
    branches:
      - mains
  pull_request:
    branches:
      - mains
  workflow_dispatch:


jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print info
        run: |
          echo "Repository URL: ${{ github.server_url }}/${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Commit URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"

      - name: checkout another repo
        id: checkout-diff-repo
        uses: actions/checkout@v4
        with:
          repository: AmitRamachandrann/cafe
          token: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Print info another repo
        run: |
          echo "Repository URL: ${{ github.server_url }}/${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Commit URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "checkout output: ${{ steps.checkout-diff-repo.outputs.commit }}"
