name: Grype scan

on:
  push:
    branches:
    - main

jobs:
  grype-codescan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Print GITHUB_RUN_ID
        run: echo "Ref name is $GITHUB_RUN_ID"

      - name: Create empty JSON file in workspace
        run: |
          FILE_PATH="$GITHUB_WORKSPACE/store/request/request.json"
          mkdir -p "$(dirname "$FILE_PATH")"
          touch "$FILE_PATH"
          echo "File created at: $FILE_PATH"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Step 4: Save the Docker image as a TAR file
      - name: Save Docker image as TAR file
        run: |
          docker save -o output.tar myapp:latest
          tar -tf output.tar
          
      - name: Grype scan
        uses: cloudbees-io-gha/grype-scan-publish@CBP-18639
        with:
          cloudbees-url: ${{ vars.CLOUDBEES_PREPROD_API_URL }}
          binary-tar-path: output.tar
